
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-dev-config
  namespace: venue-dev
  labels:
    app: traefik-dev
data:
  traefik.toml: |
    # traefik.toml
    [kubernetes]
    namespaces = ["venue-dev"]