kind: Service
apiVersion: v1
metadata:
  name: django-service
  annotations:
    # service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # TODO: Fill in with the ARN of your certificate.
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ca-central-1:854376586701:certificate/380d528a-555f-4673-904b-0c2cdc6758d9
    # Only run SSL on the port named "https" below.
    
spec:
  type: ClusterIP
  loadBalancerIP:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
      name: external
  selector:
    application: django-service