# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 13:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpdateTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=35)),
                ('date_started', models.DateTimeField(default=django.utils.timezone.now)),
                ('success', models.NullBooleanField()),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForumProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_user_id', models.CharField(max_length=50)),
                ('signature_code', models.CharField(max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ForumSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('scraper_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_posts', models.IntegerField()),
                ('total_posts_with_sig', models.IntegerField()),
                ('total_days', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Global stats',
            },
        ),
        migrations.CreateModel(
            name='PointsCalculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_calculated', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('post_days_points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('influence_points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_points', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=30)),
                ('traceback', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_resolved', models.DateTimeField(blank=True, null=True)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraping_errors', to='venue.ForumSite')),
                ('forum_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraping_errors', to='venue.ForumProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('forum_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_types', to='venue.ForumSite')),
            ],
        ),
        migrations.CreateModel(
            name='SignatureCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_checked', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_posts', models.IntegerField(default=0)),
                ('signature_found', models.BooleanField(default=True)),
                ('forum_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regular_checks', to='venue.ForumProfile')),
            ],
        ),
        migrations.CreateModel(
            name='UptimeBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('date_ended', models.DateTimeField(blank=True, null=True)),
                ('forum_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uptime_batches', to='venue.ForumProfile')),
            ],
            options={
                'verbose_name_plural': 'Uptime batches',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='signaturecheck',
            name='uptime_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regular_checks', to='venue.UptimeBatch'),
        ),
        migrations.AddField(
            model_name='pointscalculation',
            name='signature_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_calculations', to='venue.SignatureCheck'),
        ),
        migrations.AddField(
            model_name='pointscalculation',
            name='uptime_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_calculations', to='venue.UptimeBatch'),
        ),
        migrations.AddField(
            model_name='forumprofile',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='venue.ForumSite'),
        ),
        migrations.AddField(
            model_name='forumprofile',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='venue.Signature'),
        ),
        migrations.AddField(
            model_name='forumprofile',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_profiles', to='venue.UserProfile'),
        ),
        migrations.AddField(
            model_name='dataupdatetask',
            name='scraping_errors',
            field=models.ManyToManyField(to='venue.ScrapingError'),
        ),
    ]
