# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalstats',
            options={'verbose_name_plural': 'Global stats'},
        ),
        migrations.AddField(
            model_name='scraperun',
            name='date_completed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='globalstats',
            name='total_days',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
