# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signature',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
