# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-19 04:05
from __future__ import unicode_literals

from django.db import migrations
from django.utils import timezone
from django.contrib.auth.hashers import make_password
import uuid


LANGUAGES = [
    {
        'id': '390887e3-ff01-424e-a3a0-6f3c2fb9dfce',
        'name': 'English',
        'code': 'en'
    },
    {
        'id': '7fe3056f-6924-4c4a-8a89-395f7f23419c',
        'name': 'French',
        'code': 'en'
    },
    {
        'id': '22ac9a32-d572-4c20-b174-bf642a5e82ce',
        'name': 'Japanese',
        'code': 'jp'
    },
    {
        'id': 'a0236dbd-2749-46d6-a904-d26f8877cf18',
        'name': 'Spanish',
        'code': 'es'
    },
    {
        'id': 'a5a08842-3c77-4810-ad0c-e6d3c14c3b6f',
        'name': 'Portuguese',
        'code': 'pt'
    },
    {
        'id': '98f69eef-f1c3-4c90-8dff-f13271b0c957',
        'name': 'Russian',
        'code': 'ru'
    },
    {
        'id': '0fb27814-ce14-4c48-9506-7bcbcf5acb1a',
        'name': 'Chinese',
        'code': 'zh'
    },
    {
        'id': 'adc87e62-9662-43fb-9d1a-08878e715713',
        'name': 'Korean',
        'code': 'ko'
    }
]


def add_languages(apps, schema_editor):
    Language = apps.get_model('venue', 'Language')
    for lang_details in LANGUAGES:
        lang = Language(**lang_details)
        lang.save()


USERS = [
    {
        'password': 'default2018',
        'is_superuser': True,
        'username': 'admin',
        'email': 'joemar.ct+admin@gmail.com',
        'is_staff': True,
        'is_active': True
    },
    {
        'password': 'default2018',
        'username': 'stingray',
        'email': 'joemar.ct+stingray@gmail.com',
        'is_active': True
    },
    {
        'password': 'default2018',
        'username': 'spiderman',
        'email': 'joemar.ct+spiderman@gmail.com',
        'is_active': True
    },
    {
        'password': 'default2018',
        'username': 'thor',
        'email': 'joemar.ct+thor@gmail.com',
        'is_active': True
    },
    {
        'password': 'default2018',
        'username': 'ironman',
        'email': 'joemar.ct+ironman@gmail.com',
        'is_active': True
    },
    {
        'password': 'default2018',
        'username': 'antman',
        'email': 'joemar.ct+antman@gmail.com',
        'is_active': True
    },
    {
        'password': 'default2018',
        'username': 'silverclaw',
        'email': 'joemar.ct+silverclaw@gmail.com',
        'is_active': True
    },
    {
        'password': 'default2018',
        'username': 'hulk',
        'email': 'joemar.ct+hulk@gmail.com',
        'is_active': True
    },
    {
        'password': 'default2018',
        'username': 'nomad',
        'email': 'joemar.ct+nomad@gmail.com',
        'is_active': True
    },
    {
        'password': 'default2018',
        'username': 'hawkeye',
        'email': 'joemar.ct+hawkeye@gmail.com',
        'is_active': True
    },
    {
        'password': 'default2018',
        'username': 'wolverine',
        'email': 'joemar.ct+wolverine@gmail.com',
        'is_active': True
    },
]


def add_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    for user_details in USERS:
        user = User(**user_details)
        user.password = make_password(user_details['password'])
        user.save()


def add_user_profiles(apps, schema_editor):
    UserProfile = apps.get_model('venue', 'UserProfile')
    User = apps.get_model('auth', 'User')
    for user in USERS:
        if 'is_superuser' not in user.keys():
            user = User.objects.get(email=user['email'])
            profile_details = {
                'id': uuid.uuid4(),
                'user': user,
                'language_id': '390887e3-ff01-424e-a3a0-6f3c2fb9dfce'
            }
            user_profile = UserProfile(**profile_details)
            user_profile.save()


FORUM_SITES = [
    {
        'id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'name': 'bitcointalk.org',
        'address': 'https://bitcointalk.org',
        'scraper_name': 'bitcointalk.py'
    }
]


def add_forum_sites(apps, schema_editor):
    ForumSite = apps.get_model('venue', 'ForumSite')
    for site_details in FORUM_SITES:
        site = ForumSite(**site_details)
        site.save()


FORUM_USER_RANKS = [
    {
        'id': '517e74d0-fd50-4043-b397-e70dc49d10f0',
        'forum_site_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'name': 'Brand new',
        'bonus_percentage': 0,
        'allowed': True
    },
    {
        'id': 'bc8bb1b2-e056-47ab-bcf1-7967a27dd6b4',
        'forum_site_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'name': 'Newbie',
        'bonus_percentage': 0,
        'allowed': True
    },
    {
        'id': '80ab6f32-774a-4043-884c-203ac6b6e218',
        'forum_site_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'name': 'Jr. Member',
        'bonus_percentage': 0,
        'allowed': True
    },
    {
        'id': '09a7ad5e-1da4-4e7b-8799-93cf70ceb6f0',
        'forum_site_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'name': 'Member',
        'bonus_percentage': 0,
        'allowed': True
    },
    {
        'id': '99c3f7d6-8adf-4594-a7d3-b64d47488c5a',
        'forum_site_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'name': 'Full Member',
        'bonus_percentage': 0,
        'allowed': True
    },
    {
        'id': 'dd1bbfa7-a3c3-4163-8c0d-b04eb84db9ad',
        'forum_site_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'name': 'Sr. Member',
        'bonus_percentage': 2,
        'allowed': True
    },
    {
        'id': '065d2e38-295e-4b31-9da8-2946aaee5be1',
        'forum_site_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'name': 'Hero Member',
        'bonus_percentage': 5,
        'allowed': True
    },
    {
        'id': '14d22df0-3462-492b-81c5-b5812d3ef777',
        'forum_site_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'name': 'Legendary',
        'bonus_percentage': 5,
        'allowed': True
    }
]


def add_forum_user_ranks(apps, schema_editor):
    ForumUserRank = apps.get_model('venue', 'ForumUserRank')
    for rank_details in FORUM_USER_RANKS:
        rank = ForumUserRank(**rank_details)
        rank.save()


SIGNATURES = [
    {
        'id': '764ab6b6-fb92-40ad-839c-4f26ee86eed8',
        'name': 'Sr. Member Design 1',
        'forum_site_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'user_ranks': [
            'dd1bbfa7-a3c3-4163-8c0d-b04eb84db9ad'
        ],
        'code': '[center][table][tr][td][url=http://volentix.com/][tt][size=2px][color=black]█▌                     ▐█\r\n██▌                   ▐██\r\n█▐█▌                 ▐█▌█\r\n█ ▐█▌ ▐█▌ █\r\n█  ▐█▌             ▐█▌  █\r\n█   ▐█▌           ▐█▌   █\r\n█    ▐█▌         ▐█▌    █\r\n█     ▐█▌       ▐█▌     █\r\n█      ▐█▌     ▐█▌      █\r\n▀███████████████████████▀\r\n  ▀█▄   ▐█▌   ▐█▌   ▄█▀\r\n    ▀█▄  ▐█▌ ▐█▌  ▄█▀\r\n      ▀█▄ ▐█ █▌ ▄█▀\r\n        ▀█▄▐█▌▄█▀\r\n  ▀███▀[/color][/size][/tt][/url][/td]\r\n\r\n[td][url=http://volentix.com/][font=arial][size=4pt][color=transparent].[/color][/size]\r\n[size=16pt][color=black]VOLENTIX[/color][/size][/font][/url][/td][td][/td][td][/td]\r\n\r\n[td][center][font=arial][b][size=8pt][color=#232c3b]█████  3rd Party DAPP Platform  █████[/color][/size]\r\n[size=16pt][url=http://volentix.com/][color=#232c3b]Decentralized[/color] [color=#f25a4a]Change[/color][/url][/size][/b][/font][/center][/td][td][/td][td][/td]\r\n\r\n[td][center][font=arial][b][size=8pt][url=http://][color=#232c3b]ANN[/color][/url]\r\n[url=https://twitter.com/VolentixDAO/][color=#232c3b]TWITTER[/color][/url]\r\n[url=][color=#232c3b]TELEGRAM[/color][/url][/size][/b][/font][/center][/td][td][/td]\r\n\r\n[td][size=4pt][color=#f25a4a]▄\r\n█\r\n█\r\n█\r\n█\r\n▀[/color][/size][/td][td][/td][td][/td]\r\n\r\n[td][center][url=http://volentix.com/][font=arial][b][size=16pt][color=black]▬ •  VENUE  • ▬[/color][/size]\r\n[size=8pt][color=#232c3b]Social Rewards Platform[/color][/size][/b][/font][/url][/center][/td][td][/td]\r\n\r\n[td][size=4pt][color=#f25a4a]▄\r\n█\r\n█\r\n█\r\n█\r\n▀[/color][/size][/td][td][/td][td][/td]\r\n\r\n[td][center][url=http://volentix.com/][font=arial][b][size=8pt][color=#232c3b]Decentralized Exchange[/color][/size]\r\n[size=16pt][color=black]▬ • VDEX • ▬[/color][/size][/b][/font][/url][/center][/td][td][/td]\r\n\r\n[td][tt][size=2px][color=#1f3150]  ▄████████▄▄       \r\n      ▄██████████████▄ \r\n    ▄████▀▀      ▀▀████▄ ▄▄\r\n   ███▀             ▀██████ \r\n  ███     ▄████▄     ██████\r\n ███     █▀    ▀█   ███████        \r\n███     ▐▌   ▄▄▄▄▄        \r\n        ▐▌  ▐▄▄▄▄▄▌        \r\n         █▄ ▐     ▌     ███ \r\n███████   ▀█▐▀▀▀▀▀▌    ███ \r\n██████       ▀▀▀▀▀    ███  \r\n██████▄             ▄███▀    \r\n▀▀ ▀████▄▄      ▄▄████▀     \r\n     ▀██████████████▀\r\n        ▀▀███████▀▀[/color][/size][/tt][/td]\r\n\r\n[td][size=4pt][color=#f25a4a]▄\r\n█\r\n█\r\n█\r\n█\r\n▀[/color][/size][/td][td][/td][td][/td]\r\n\r\n[td][center][tt][size=2px]\r\n\r\n\r\n▄▄███████████▄▄\r\n▄█▀▀           ▀▀█▄\r\n▄█    █       █    █▄\r\n█▌    ██     ██    ▐█\r\n█▌    █ █   █ █    ▐█\r\n█▌    █  █ █  █    ▐█\r\n█▌    ▀█▀▀█▀▀█▀    ▐█\r\n▀█      ▀███▀      █▀\r\n▀█▄▄           ▄▄█▀\r\n▀▀███████████▀▀[/size][/tt][/center][/td]\r\n\r\n[td][size=5px][color=transparent].[/color][/size]\r\n[font=arial][b][size=13px][color=#e22b2b]BETA TESTER[/color][/size]\r\n[size=8px]Designed by Zpectrum[/size][/b][/font][/td][/tr][/table][/center]',
        'expected_links': 'http://volentix.com/\r\nhttps://twitter.com/VolentixDAO/',
        'test_signature': 'Love For All, Hatred For None',
        'image': 'uploads/sig_bf01f803-9e25-402b-ab42-e5896b42fea0.png',
        'active': True,
        'date_added': '2018-06-14 12:03:50+00:00'
    },
    {
        'id': '0a7dd7cd-8f3b-48ca-989c-d4ec550b136d',
        'name': 'Sr. Member Design 2',
        'forum_site_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'user_ranks': [
            'dd1bbfa7-a3c3-4163-8c0d-b04eb84db9ad'
        ],
        'code': '[center][table][tr][td][center][font=arial][b][size=16pt]VESPUCCI[/size]\r\n[size=8pt][color=#232c3b]Analytical Engine[/color][/size][/b][/font][/center][/td][td][/td]\r\n\r\n[td][tt][size=2px][color=#232c3b]\r\n\r\n                                [color=#777777]▄████▄▄   ▄██[/color]\r\n                              [color=#777777]▄█▀    ▀▀███▀[/color]\r\n                           [color=#777777]▄███▀[/color]\r\n    [color=#777777]▄▄██████▄▄          ▄███▀▀[/color]   ▄███▄\r\n  [color=#777777]▄████████████▄     ▄██▀[/color]    ▄█████████▄\r\n [color=#777777]██████████████████ ██▀[/color]  ▄███████████████▄\r\n [color=#777777]████████████████████[/color]  ▄███████████████████▄\r\n[color=#777777]██████████[/color]███████████████████████████████████\r\n[color=#777777]█████████[/color]████████████████████████████████████\r\n[color=#777777]███████[/color]██████████████████████████████████████\r\n█████████████████████████████████████████████\r\n█████████████████████████████████████████████\r\n█████████████████████████████████████████████[/color][/size][/tt][/td][td][/td]\r\n\r\n[td][center][url=http://volentix.com/][font=arial][b][size=16pt][color=black]▬ •  VENUE  • ▬[/color][/size]\r\n[size=8pt][color=#232c3b]Social Rewards Platform[/color][/size][/b][/font][/url][/center][/td][td][/td]\r\n\r\n[td][size=2pt][color=#ec6d5a]\r\n██\r\n██\r\n██\r\n██\r\n██\r\n██\r\n██\r\n██\r\n██\r\n██[/color][/size][/td][td][/td][td][/td]\r\n\r\n[td][url=https://volentix.com/][tt][size=2px][color=black]█▌                     ▐█\r\n██▌                   ▐██\r\n█▐█▌                 ▐█▌█\r\n█ ▐█▌               ▐█▌ █\r\n█  ▐█▌             ▐█▌  █\r\n█   ▐█▌           ▐█▌   █\r\n█    ▐█▌         ▐█▌    █\r\n█     ▐█▌       ▐█▌     █\r\n█      ▐█▌     ▐█▌      █\r\n▀███████████████████████▀\r\n  ▀█▄   ▐█▌   ▐█▌   ▄█▀\r\n    ▀█▄  ▐█▌ ▐█▌  ▄█▀\r\n      ▀█▄ ▐█ █▌ ▄█▀\r\n        ▀█▄▐█▌▄█▀\r\n          ▀███▀[/color][/size][/tt][/url][/td]\r\n\r\n[td][url=https://volentix.com/][font=arial][b][size=16pt][color=black]VOLENTIX[/color][/size]\r\n[size=8pt][color=#232c3b]Decentralized[/color] [color=#f25a4a]Change[/color][/size][/b][/font][/url][/td][td][/td]\r\n\r\n[td][center][font=arial][b][size=8pt][url=http://][color=#232c3b]ANN[/color][/url]\r\n[url=https://twitter.com/VolentixDAO/][color=#232c3b]TWITTER[/color][/url]\r\n[url=][color=#232c3b]TELEGRAM[/color][/url][/size][/b][/font][/center][/td][td][/td]\r\n\r\n[td][center][tt][size=2px]\r\n\r\n\r\n▄▄███████████▄▄\r\n▄█▀▀      ▀▀█▄\r\n▄█    █       █    █▄\r\n█▌    ██     ██    ▐█\r\n█▌    █ █   █ █    ▐█\r\n█▌    █  █ █  █    ▐█\r\n█▌    ▀█▀▀█▀▀█▀    ▐█\r\n▀█   ▀███▀      █▀\r\n▀█▄▄           ▄▄█▀\r\n▀▀███████████▀▀[/size][/tt][/center][/td]\r\n\r\n[td][size=5px][color=transparent].[/color][/size]\r\n[font=arial][b][size=13px][color=#e22b2b]BETA TESTER[/color][/size]\r\n[size=8px]Designed by Zpectrum[/size][/b][/font][/td][td][/td][td][/td]\r\n\r\n[td][size=2pt][color=#ec6d5a]\r\n██\r\n██\r\n██\r\n██\r\n██\r\n██\r\n██\r\n██\r\n██\r\n██[/color][/size][/td][td][/td][td][/td]\r\n\r\n[td][center][url=http://volentix.com/][font=arial][b][size=16pt][color=black]▬ • VDEX • ▬[/color][/size]\r\n[size=8pt][color=#232c3b]Decentralized Exchange[/color][/size][/b][/font][/url][/center][/td][td][/td]\r\n\r\n[td][tt][size=2px][color=#232c3b]       ▄██▄\r\n     ▄▐████▌▄▄▄ ▄██▄\r\n ▄▄ ▀  ▀██▀    ▐████▌\r\n▐██▌     ▀▄▄  █ ▀██▀▀▄\r\n▄▀▀ ▄    ████   ▄ ▄  ▄█▄\r\n█    ▀▄▄▀ ▀▀▄  ▀   █ ▀█▀\r\n ▄ ▄▄▀██    ▄███▄ ▄▀▄  ▌\r\n███ ▄▐█████▌  ▄██▄\r\n ▀ ▄ ▄  ▄▀  ▀███▀  ▐████▌\r\n    ███    ▄▀   ▀▄  ▀██▀\r\n     ▀▀▄███▄     ▄██▄▀\r\n      ███████   ▐████▌\r\n     ▐███████▌▄▀ ▀██▀\r\n      ███████\r\n       ▀███▀[/color][/size][/tt][/td]\r\n\r\n[td][center][font=arial][b][size=16pt]VCHAIN[/size]\r\n[size=8pt]▬▬▬▬▬▬▬▬[/size][/b][/font][/center][/td][/tr][/table][/center]',
        'expected_links': 'http://volentix.com/\r\nhttps://twitter.com/VolentixDAO/',
        'test_signature': 'Change the world by being yourself',
        'image': 'uploads/sig_2c96827b-907a-44e0-86ad-8e2eab146415.png',
        'active': True,
        'date_added': '2018-06-14 12:03:50+00:00'
    },
    {
        'id': 'dc45d74f-26f8-4359-a9a5-92ee8540651f',
        'name': 'Sr. Member Design 3',
        'forum_site_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'user_ranks': [
            'dd1bbfa7-a3c3-4163-8c0d-b04eb84db9ad'
        ],
        'code': '[center][table][tr][td][table][tr][td][url=http://volentix.com/][tt][size=2px][color=black]█▌                     ▐█\r\n██▌                   ▐██\r\n█▐█▌                 ▐█▌█\r\n█ ▐█▌               ▐█▌ █\r\n█  ▐█▌             ▐█▌  █\r\n█   ▐█▌           ▐█▌   █\r\n█    ▐█▌         ▐█▌    █\r\n█     ▐█▌       ▐█▌     █\r\n█    ▐█▌     ▐█▌      █\r\n▀███████████████████████▀\r\n  ▀█▄   ▐█▌   ▐█▌   ▄█▀\r\n    ▀█▄  ▐█▌ ▐█▌  ▄█▀\r\n      ▀█▄ ▐█ █▌ ▄█▀\r\n        ▀█▄▐█▌▄█▀\r\n          ▀███▀[/color][/size][/tt][/url][/td]\r\n\r\n[td][url=http://volentix.com/][font=arial][size=4pt][color=transparent].[/color][/size]\r\n[size=16pt][color=black]VOLENTIX[/color][/size][/font][/url][/td][td][/td][td][/td]\r\n\r\n[td][center][font=arial][b][size=16pt][url=http://volentix.com/][color=#232c3b]Decentralized[/color] [color=#f25a4a]Change[/color][/url][/size]\r\n[size=8pt][color=#f25a4a]▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬[/color]  [url=http://][color=black]ANN[/color][/url][/size][/b][/font][/center][/td][td][/td][td][/td]\r\n\r\n[td][size=6px][color=transparent].[/color][/size]\r\n[url=https://twitter.com/VolentixDAO/][tt][size=2px][color=#00aced]                ▄█████▄▄    \r\n█▄             ████████████▀ \r\n████▄         █████████████▀ \r\n▀████████▄▄   ████████████\r\n▄▄████████████████████████\r\n █████████████████████████\r\n ▀███████████████████████ \r\n   █████████████████████ \r\n    ▀█████████████████▀\r\n      ▄█████████████▀\r\n▄▄███████████████▀ \r\n   ▀▀▀▀▀▀▀▀▀▀▀[/color][/size][/tt][/url][/td][td][/td]\r\n\r\n[td][size=6px][color=transparent].[/color][/size]\r\n[url=][tt][size=2px][color=#2ca5e0]      ▄▄████\r\n                ▄▄▄████████▌\r\n          ▄▄▄███████▀▄█████\r\n     ▄▄█████████▀▀ ▄██████▌\r\n▄▄███████████▀  ▄█████████\r\n ▀▀▀█████▀    ▄██████████▌\r\n       ██   █████████████\r\n        █▄ █████████████▌\r\n        ▐█▄███▀▀████████\r\n         ███▀    ▀▀████▌\r\n                ▀▀█[/color][/size][/tt][/url][/td][td][/td][td][/td]\r\n\r\n[td][size=2pt][color=#ec6d5a]\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█[/color][/size][/td][td][/td][td][/td]\r\n\r\n[td][center][url=http://volentix.com/][font=arial][b][size=8pt][color=#232c3b]Analytical Engine • VESPUCCI   |   VCHAIN • Blockchain Technology\r\n[color=#f25a4a]▬▬▬▬▬▬▬▬▬▬  3rd Party DAPP Platform  ▬▬▬▬▬▬▬▬▬▬[/color]\r\nSocial Rewards Platform • VENUE   |   VDEX • Decentralized Exchange[/color][/size][/b][/font][/url][/center][/td][td][/td][td][/td]\r\n\r\n[td][size=2pt][color=#ec6d5a]\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█[/color][/size][/td][td][/td][td][/td]\r\n\r\n[td][center][tt][size=2px][url=https://bitcointalk.org/index.php?topic=2221211][/url]\r\n\r\n\r\n▄▄███████████▄▄\r\n▄█▀▀           ▀▀█▄\r\n▄█    █       █    █▄\r\n█▌    ██     ██    ▐█\r\n█▌    █ █   █ █    ▐█\r\n█▌    █  █ █  █    ▐█\r\n█▌    ▀█▀▀█▀▀█▀    ▐█\r\n▀█      ▀███▀      █▀\r\n▀█▄▄           ▄▄█▀\r\n▀▀███████████▀▀[/size][/tt][/center][/td]\r\n\r\n[td][size=5px][color=transparent].[/color][/size]\r\n[font=arial][b][size=13px][color=#e22b2b]BETA TESTER[/color][/size]\r\n[size=8px]Designed by Zpectrum[/size][/b][/font][/td][/tr][/table][/center]',
        'expected_links': 'http://volentix.com/\r\nhttps://twitter.com/VolentixDAO/\r\nhttps://bitcointalk.org/index.php?topic=2221211',
        'test_signature': 'Every moment is a fresh beginning',
        'image': 'uploads/sig_bf4ec904-012e-49ca-9e3c-e7ccaa663fc1.png',
        'active': True,
        'date_added': '2018-06-14 12:03:50+00:00'
    },
    {
        'id': '5c739ddd-2046-40d1-a058-ce833b27b458',
        'name': 'Sr. Member Design 4',
        'forum_site_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'user_ranks': [
            'dd1bbfa7-a3c3-4163-8c0d-b04eb84db9ad'
        ],
        'code': '[center][table][tr][td][table][tr][td][url=http://volentix.com/][tt][size=2px][color=black]█▌                     ▐█\r\n██▌                   ▐██\r\n█▐█▌                 ▐█▌█\r\n█ ▐█▌               ▐█▌ █\r\n█  ▐█▌             ▐█▌  █\r\n█   ▐█▌           ▐█▌   █\r\n█    ▐█▌         ▐█▌    █\r\n█     ▐█▌       ▐█▌     █\r\n█    ▐█▌     ▐█▌      █\r\n▀███████████████████████▀\r\n  ▀█▄   ▐█▌   ▐█▌   ▄█▀\r\n    ▀█▄  ▐█▌ ▐█▌  ▄█▀\r\n      ▀█▄ ▐█ █▌ ▄█▀\r\n        ▀█▄▐█▌▄█▀\r\n          ▀███▀[/color][/size][/tt][/url][/td]\r\n\r\n[td][url=http://volentix.com/][font=arial][size=4pt][color=transparent].[/color][/size]\r\n[size=16pt][color=black]VOLENTIX[/color][/size][/font][/url][/td][td][/td][td][/td]\r\n\r\n[td][center][font=arial][b][size=16pt][url=http://volentix.com/][color=#232c3b]Decentralized[/color] [color=#f25a4a]Change[/color][/url][/size]\r\n[size=8pt][color=#f25a4a]▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬[/color]  [url=http://][color=black]ANN[/color][/url][/size][/b][/font][/center][/td][td][/td][td][/td]\r\n\r\n[td][size=6px][color=transparent].[/color][/size]\r\n[url=https://twitter.com/VolentixDAO/][tt][size=2px][color=#232c3b]                ▄█████▄▄    \r\n█▄             ████████████▀ \r\n████▄         █████████████▀ \r\n▀████████▄▄   ████████████\r\n▄▄████████████████████████\r\n █████████████████████████\r\n ▀███████████████████████ \r\n   █████████████████████ \r\n    ▀█████████████████▀\r\n      ▄█████████████▀\r\n▄▄███████████████▀ \r\n   ▀▀▀▀▀▀▀▀▀▀▀[/color][/size][/tt][/url][/td][td][/td]\r\n\r\n[td][size=6px][color=transparent].[/color][/size]\r\n[url=][tt][size=2px][color=#232c3b]      ▄▄████\r\n                ▄▄▄████████▌\r\n          ▄▄▄███████▀▄█████\r\n     ▄▄█████████▀▀ ▄██████▌\r\n▄▄███████████▀  ▄█████████\r\n ▀▀▀█████▀    ▄██████████▌\r\n       ██   █████████████\r\n        █▄ █████████████▌\r\n        ▐█▄███▀▀████████\r\n         ███▀    ▀▀████▌\r\n                ▀▀█[/color][/size][/tt][/url][/td][td][/td][td][/td]\r\n\r\n[td][size=2pt][color=#ec6d5a]\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█[/color][/size][/td][td][/td][td][/td]\r\n\r\n[td][center][url=http://volentix.com/][font=arial][b][size=8pt][color=#232c3b]Analytical Engine • VESPUCCI   |   VCHAIN • Blockchain Technology\r\n[color=#f25a4a]▬▬▬▬▬▬▬▬▬▬  3rd Party DAPP Platform  ▬▬▬▬▬▬▬▬▬▬[/color]\r\nSocial Rewards Platform • VENUE   |   VDEX • Decentralized Exchange[/color][/size][/b][/font][/url][/center][/td][td][/td][td][/td]\r\n\r\n[td][size=2pt][color=#ec6d5a]\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█[/color][/size][/td][td][/td][td][/td]\r\n\r\n[td][center][tt][size=2px][url=https://bitcointalk.org/index.php?topic=2221211][/url]\r\n\r\n\r\n▄▄███████████▄▄\r\n▄█▀▀           ▀▀█▄\r\n▄█    █       █    █▄\r\n█▌    ██     ██    ▐█\r\n█▌    █ █   █ █    ▐█\r\n█▌    █  █ █  █    ▐█\r\n█▌    ▀█▀▀█▀▀█▀    ▐█\r\n▀█      ▀███▀      █▀\r\n▀█▄▄           ▄▄█▀\r\n▀▀███████████▀▀[/size][/tt][/center][/td]\r\n\r\n[td][size=5px][color=transparent].[/color][/size]\r\n[font=arial][b][size=13px][color=#e22b2b]BETA TESTER[/color][/size]\r\n[size=8px]Designed by Zpectrum[/size][/b][/font][/td][/tr][/table][/center]',
        'expected_links': 'http://volentix.com/\r\nhttps://twitter.com/VolentixDAO/\r\nhttps://bitcointalk.org/index.php?topic=2221211',
        'test_signature': 'Never regret anything that made you smile',
        'image': 'uploads/sig_a896372c-a418-451f-af42-1ddb6c8d96f7.png',
        'active': True,
        'date_added': '2018-06-14 12:03:50+00:00'
    },
    {
        'id': 'e85eb8bb-2657-4081-b48f-f5da75030b3b',
        'name': 'Hero/Legendary Member Design 1',
        'forum_site_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'user_ranks': [
            '065d2e38-295e-4b31-9da8-2946aaee5be1',
            '14d22df0-3462-492b-81c5-b5812d3ef777'
        ],
        'code': '[center][table][tr][td][url=http://volentix.com/][tt][size=2px][color=black]█▌                     ▐█\r\n██▌                   ▐██\r\n█▐█▌                 ▐█▌█\r\n█ ▐█▌            ▐█▌ █\r\n█  ▐█▌             ▐█▌  █\r\n█   ▐█▌           ▐█▌   █\r\n█    ▐█▌         ▐█▌    █\r\n█     ▐█▌       ▐█▌     █\r\n█▐█▌     ▐█▌      █\r\n▀███████████████████████▀\r\n  ▀█▄   ▐█▌   ▐█▌   ▄█▀\r\n    ▀█▄  ▐█▌ ▐█▌  ▄█▀\r\n      ▀█▄ ▐█ █▌ ▄█▀\r\n        ▀█▄▐█▌▄█▀\r\n          ▀███▀[/color][/size][/tt][/url][/td]\r\n\r\n[td][url=http://volentix.com/][font=arial][size=4pt][color=transparent].[/color][/size]\r\n[size=16pt][color=black]VOLENTIX[/color][/size][/font][/url][/td][td][/td][td][/td]\r\n\r\n[td][center][font=arial][b][size=8pt][glow=#232c3b,2,300][color=white][color=transparent]...............[/color]3rd Party DAPP Platform[color=transparent]...............[/color][/color][/glow][/size]\r\n[size=16pt][url=http://volentix.com/][color=#232c3b]Decentralized[/color] [color=#f25a4a]Change[/color][/url][/size][/b][/font][/center][/td][td][/td][td][/td]\r\n\r\n[td][center][font=arial][b][size=8pt][url=http://][color=#232c3b]ANN[/color][/url]\r\n[url=https://twitter.com/VolentixDAO/][color=#232c3b]TWITTER[/color][/url]\r\n[url=][color=#232c3b]TELEGRAM[/color][/url][/size][/b][/font][/center][/td][td][/td]\r\n\r\n[td][size=4pt][color=#f25a4a]▄\r\n█\r\n█\r\n█\r\n█\r\n▀[/color][/size][/td][td][/td][td][/td]\r\n\r\n[td][center][url=http://volentix.com/][font=arial][b][size=16pt][color=black]▬ •  VENUE  • ▬[/color][/size]\r\n[size=8pt][glow=#232c3b,2,300][color=white][color=transparent]......[/color]Social Rewards Platform[color=transparent]......[/color][/color][/glow][/size][/b][/font][/url][/center][/td][td][/td]\r\n\r\n[td][size=4pt][color=#f25a4a]▄\r\n█\r\n█\r\n█\r\n█\r\n▀[/color][/size][/td][td][/td][td][/td]\r\n\r\n[td][center][url=http://volentix.com/][font=arial][b][size=8pt][glow=#232c3b,2,300][color=white][color=transparent]...[/color]Decentralized Exchange[color=transparent]...[/color][/color][/glow][/size]\r\n[size=16pt][color=black]▬ • VDEX • ▬[/color][/size][/b][/font][/url][/center][/td][td][/td]\r\n\r\n[td][tt][size=2px][color=#1f3150]        ▄████████▄▄       \r\n      ▄██████████████▄ \r\n    ▄████▀▀      ▀▀████▄ ▄▄\r\n   ███▀             ▀██████ \r\n  ███     ▄████▄     ██████\r\n ███    █▀    ▀█   ███████        \r\n███     ▐▌   ▄▄▄▄▄        \r\n        ▐▌  ▐▄▄▄▄▄▌        \r\n         █▄ ▐     ▌     ███ \r\n███████   ▀█▐▀▀▀▀▀▌    ███ \r\n██████       ▀▀▀▀▀    ███  \r\n██████▄             ▄███▀    \r\n▀▀ ▀████▄▄      ▄▄████▀     \r\n     ▀██████████████▀       \r\n      ▀▀███████▀▀[/color][/size][/tt][/td]\r\n\r\n[td][size=4pt][color=#f25a4a]▄\r\n█\r\n█\r\n█\r\n█\r\n▀[/color][/size][/td][td][/td][td][/td]\r\n\r\n[td][center][tt][size=2px]\r\n\r\n\r\n▄▄███████████▄▄\r\n▄█▀▀           ▀▀█▄\r\n▄█    █       █    █▄\r\n█▌    ██     ██    ▐█\r\n█▌    █ █   █ █    ▐█\r\n█▌    █  █ █  █    ▐█\r\n█▌    ▀█▀▀█▀▀█▀    ▐█\r\n▀█      ▀███▀      █▀\r\n▀█▄▄           ▄▄█▀\r\n▀▀███████████▀▀[/size][/tt][/center][/td]\r\n\r\n[td][size=5px][color=transparent].[/color][/size]\r\n[font=arial][b][size=13px][color=#e22b2b]BETA TESTER[/color][/size]\r\n[size=8px]Designed by Zpectrum[/size][/b][/font][/td][/tr][/table][/center]',
        'expected_links': 'http://volentix.com/\r\nhttps://twitter.com/VolentixDAO/',
        'test_signature': 'Die with memories, not dreams',
        'image': 'uploads/sig_95a98747-4606-4911-bfe8-e68118ac98a6.png',
        'active': True,
        'date_added': '2018-06-14 12:03:50+00:00'
    },
    {
        'id': '9537b3d7-4d7f-41ba-8055-be8ed5f8ea28',
        'name': 'Hero/Legendary Member Design 2',
        'forum_site_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'user_ranks': [
            '065d2e38-295e-4b31-9da8-2946aaee5be1',
            '14d22df0-3462-492b-81c5-b5812d3ef777'
        ],
        'code': '[center][table][tr][td][center][font=arial][b][size=16pt]VESPUCCI[/size]\r\n[size=8pt][glow=#232c3b,2,300][color=white][color=transparent]....[/color]Analytical Engine[color=transparent]....[/color][/color][/glow][/size][/b][/font][/center][/td][td][/td]\r\n\r\n[td][tt][size=2px][color=#232c3b]\r\n\r\n                    [color=#777777]▄████▄▄   ▄██[/color]\r\n                              [color=#777777]▄█▀    ▀▀███▀[/color]\r\n             [color=#777777]▄███▀[/color]\r\n    [color=#777777]▄▄██████▄▄          ▄███▀▀[/color]   ▄███▄\r\n  [color=#777777]▄████████████▄  ▄██▀[/color]    ▄█████████▄\r\n [color=#777777]██████████████████ ██▀[/color]  ▄███████████████▄\r\n [color=#777777]████████████████████[/color]  ▄███████████████████▄\r\n[color=#777777]██████████[/color]███████████████████████████████████\r\n[color=#777777]█████████[/color]████████████████████████████████████\r\n[color=#777777]███████[/color]██████████████████████████████████████\r\n█████████████████████████████████████████████\r\n█████████████████████████████████████████████\r\n█████████████████████████████████████████████[/color][/size][/tt][/td][td][/td]\r\n\r\n[td][center][url=http://volentix.com/][font=arial][b][size=16pt][color=black]▬ •  VENUE  • ▬[/color][/size]\r\n[size=8pt][glow=#232c3b,2,300][color=white][color=transparent]......[/color]Social Rewards Platform[color=transparent]......[/color][/color][/glow][/size][/b][/font][/url][/center][/td][td][/td]\r\n\r\n[td][size=2pt][color=#ec6d5a]\r\n██\r\n██\r\n██\r\n██\r\n██\r\n██\r\n██\r\n██\r\n██\r\n██[/color][/size][/td][td][/td][td][/td]\r\n\r\n[td][url=https://volentix.com/][tt][size=2px][color=black]█▌                     ▐█\r\n██▌                   ▐██\r\n█▐█▌       ▐█▌█\r\n█ ▐█▌               ▐█▌ █\r\n█  ▐█▌             ▐█▌  █\r\n█   ▐█▌           ▐█▌   █\r\n█    ▐█▌         ▐█▌    █\r\n█     ▐█▌   ▐█▌     █\r\n█      ▐█▌     ▐█▌      █\r\n▀███████████████████████▀\r\n  ▀█▄   ▐█▌   ▐█▌   ▄█▀\r\n    ▀█▄  ▐█▌ ▐█▌  ▄█▀\r\n      ▀█▄ ▐█ █▌ ▄█▀\r\n        ▀█▄▐█▌▄█▀\r\n          ▀███▀[/color][/size][/tt][/url][/td]\r\n\r\n[td][url=https://volentix.com/][font=arial][b][size=16pt][color=black]VOLENTIX[/color][/size]\r\n[size=8pt][color=#232c3b]Decentralized[/color] [color=#f25a4a]Change[/color][/size][/b][/font][/url][/td][td][/td]\r\n\r\n[td][center][font=arial][b][size=8pt][url=http://][color=#232c3b]ANN[/color][/url]\r\n[url=https://twitter.com/VolentixDAO/][color=#232c3b]TWITTER[/color][/url]\r\n[url=][color=#232c3b]TELEGRAM[/color][/url][/size][/b][/font][/center][/td][td][/td]\r\n\r\n[td][center][tt][size=2px]\r\n\r\n\r\n▄▄███████████▄▄\r\n▄█▀▀           ▀▀█▄\r\n▄█    █       █    █▄\r\n█▌    ██     ██    ▐█\r\n█▌    █ █   █ █    ▐█\r\n█▌    █  █ █  █    ▐█\r\n█▌    ▀█▀▀█▀▀█▀    ▐█\r\n▀█      ▀███▀      █▀\r\n▀█▄▄           ▄▄█▀\r\n▀▀███████████▀▀[/size][/tt][/center][/td]\r\n\r\n[td][size=5px][color=transparent].[/color][/size]\r\n[font=arial][b][size=13px][color=#e22b2b]BETA TESTER[/color][/size]\r\n[size=8px]Designed by Zpectrum[/size][/b][/font][/td][td][/td][td][/td]\r\n\r\n[td][size=2pt][color=#ec6d5a]\r\n██\r\n██\r\n██\r\n██\r\n██\r\n██\r\n██\r\n██\r\n██\r\n██[/color][/size][/td][td][/td][td][/td]\r\n\r\n[td][center][url=http://volentix.com/][font=arial][b][size=16pt][color=black]▬ • VDEX • ▬[/color][/size]\r\n[size=8pt][glow=#232c3b,2,300][color=white][color=transparent]...[/color]Decentralized Exchange[color=transparent]...[/color][/color][/glow][/size][/b][/font][/url][/center][/td][td][/td]\r\n\r\n[td][tt][size=2px][color=#232c3b]       ▄██▄\r\n     ▄▐████▌▄▄▄ ▄██▄\r\n ▄▄ ▀  ▀██▀ ▐████▌\r\n▐██▌     ▀▄▄  █ ▀██▀▀▄\r\n▄▀▀ ▄    ████   ▄ ▄  ▄█▄\r\n█    ▀▄▄▀ ▀▀▄  ▀   █ ▀█▀\r\n ▄ ▄▄▀██    ▄███▄ ▄▀▄  ▌\r\n███       ▄▐█████▌  ▄██▄\r\n ▀ ▄ ▄  ▄▀  ▀███▀  ▐████▌\r\n    ███    ▄▀   ▀▄  ▀██▀\r\n     ▀▀▄███▄     ▄██▄▀\r\n      ███████   ▐████▌\r\n     ▐███████▌▄▀ ▀██▀\r\n ███████\r\n       ▀███▀[/color][/size][/tt][/td]\r\n\r\n[td][center][font=arial][b][size=16pt]VCHAIN[/size]\r\n[size=8pt]▬▬▬▬▬▬▬▬[/size][/b][/font][/center][/td][/tr][/table][/center]',
        'expected_links': 'http://volentix.com/\r\nhttps://twitter.com/VolentixDAO/',
        'test_signature': 'Aspire to inspire before we expire',
        'image': 'uploads/sig_a89e9efd-9a5c-4d00-806b-a141027c19e9.png',
        'active': True,
        'date_added': '2018-06-14 12:03:50+00:00'
    },
    {
        'id': '5a506e4d-f5b6-408e-9e00-39f5b7521351',
        'name': 'Hero/Legendary Member Design 3',
        'forum_site_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'user_ranks': [
            '065d2e38-295e-4b31-9da8-2946aaee5be1',
            '14d22df0-3462-492b-81c5-b5812d3ef777'
        ],
        'code': '[center][table][tr][td][table][tr][td][url=http://volentix.com/][tt][size=2px][color=black]█▌                     ▐█\r\n██▌                   ▐██\r\n█▐█▌                 ▐█▌█\r\n█ ▐█▌               ▐█▌ █\r\n█  ▐█▌             ▐█▌  █\r\n█   ▐█▌           ▐█▌   █\r\n█    ▐█▌         ▐█▌    █\r\n█     ▐█▌       ▐█▌   █\r\n█      ▐█▌     ▐█▌      █\r\n▀███████████████████████▀\r\n  ▀█▄   ▐█▌   ▐█▌   ▄█▀\r\n    ▀█▄  ▐█▌ ▐█▌  ▄█▀\r\n      ▀█▄ ▐█ █▌ ▄█▀\r\n     ▀█▄▐█▌▄█▀\r\n          ▀███▀[/color][/size][/tt][/url][/td]\r\n\r\n[td][url=http://volentix.com/][font=arial][size=4pt][color=transparent].[/color][/size]\r\n[size=16pt][color=black]VOLENTIX[/color][/size][/font][/url][/td][td][/td][td][/td]\r\n\r\n[td][center][font=arial][b][size=16pt][url=http://volentix.com/][glow=#232c3b,2,300][color=transparent]...[/color][color=white]Decentralized[/color] [color=#f25a4a]Change[/color][color=transparent]...[/color][/glow][/url][/size]\r\n[size=8pt][color=#f25a4a]▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬[/color]  [url=http://][color=black]ANN[/color][/url][/size][/b][/font][/center][/td][td][/td][td][/td]\r\n\r\n[td][size=6px][color=transparent].[/color][/size]\r\n[url=https://twitter.com/VolentixDAO/][tt][size=2px][color=#00aced]                ▄█████▄▄    \r\n█▄             ████████████▀ \r\n████▄         █████████████▀ \r\n▀████████▄▄   ████████████\r\n▄▄████████████████████████\r\n █████████████████████████\r\n ▀███████████████████████ \r\n   █████████████████████ \r\n    ▀█████████████████▀\r\n      ▄█████████████▀\r\n▄▄███████████████▀ \r\n   ▀▀▀▀▀▀▀▀▀▀▀[/color][/size][/tt][/url][/td][td][/td]\r\n\r\n[td][size=6px][color=transparent].[/color][/size]\r\n[url=][tt][size=2px][color=#2ca5e0]                      ▄▄████\r\n                ▄▄▄████████▌\r\n          ▄▄▄███████▀▄█████\r\n     ▄▄█████████▀▀ ▄██████▌\r\n▄▄███████████▀  ▄█████████\r\n ▀▀▀█████▀    ▄██████████▌\r\n       ██   █████████████\r\n        █▄ █████████████▌\r\n        ▐█▄███▀▀████████\r\n         ███▀    ▀▀████▌\r\n                    ▀▀█[/color][/size][/tt][/url][/td][td][/td][td][/td]\r\n\r\n[td][size=2pt][color=#ec6d5a]\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█[/color][/size][/td][td][/td][td][/td]\r\n\r\n[td][center][url=http://volentix.com/][font=arial][b][size=8pt][color=#232c3b]Analytical Engine • VESPUCCI   |   VCHAIN • Blockchain Technology\r\n[glow=#f25a4a,2,300][color=white][color=transparent]....[/color]▬▬▬▬▬▬▬▬▬  3rd Party DAPP Platform  ▬▬▬▬▬▬▬▬▬[color=transparent]....[/color][/color][/glow]\r\nSocial Rewards Platform • VENUE   |   VDEX • Decentralized Exchange[/color][/size][/b][/font][/url][/center][/td][td][/td][td][/td]\r\n\r\n[td][size=2pt][color=#ec6d5a]\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█[/color][/size][/td][td][/td][td][/td]\r\n\r\n[td][center][tt][size=2px][url=https://bitcointalk.org/index.php?topic=2221211][/url]\r\n\r\n\r\n▄▄███████████▄▄\r\n▄█▀▀           ▀▀█▄\r\n▄█    █       █    █▄\r\n█▌    ██     ██    ▐█\r\n█▌    █ █   █ █    ▐█\r\n█▌    █  █ █  █    ▐█\r\n█▌    ▀█▀▀█▀▀█▀    ▐█\r\n▀█      ▀███▀ █▀\r\n▀█▄▄           ▄▄█▀\r\n▀▀███████████▀▀[/size][/tt][/center][/td]\r\n\r\n[td][size=5px][color=transparent].[/color][/size]\r\n[font=arial][b][size=13px][color=#e22b2b]BETA TESTER[/color][/size]\r\n[size=8px]Designed by Zpectrum[/size][/b][/font][/td][/tr][/table][/center]',
        'expected_links': 'http://volentix.com/\r\nhttps://twitter.com/VolentixDAO/\r\nhttps://bitcointalk.org/index.php?topic=2221211',
        'test_signature': 'Everything you can imagine is real',
        'image': 'uploads/sig_8e5abcf7-5062-4603-baba-99a932276f14.png',
        'active': True,
        'date_added': '2018-06-14 12:03:50+00:00'
    },
    {
        'id': 'ac84e67b-077f-453c-a1f8-b63bac745bf3',
        'name': 'Hero/Legendary Member Design 4',
        'forum_site_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'user_ranks': [
            '065d2e38-295e-4b31-9da8-2946aaee5be1',
            '14d22df0-3462-492b-81c5-b5812d3ef777'
        ],
        'code': '[center][table][tr][td][table][tr][td][url=http://volentix.com/][tt][size=2px][color=black]█▌                     ▐█\r\n██▌                   ▐██\r\n█▐█▌                 ▐█▌█\r\n█ ▐█▌               ▐█▌ █\r\n█  ▐█▌             ▐█▌  █\r\n█   ▐█▌           ▐█▌   █\r\n█    ▐█▌         ▐█▌    █\r\n█     ▐█▌       ▐█▌   █\r\n█      ▐█▌     ▐█▌      █\r\n▀███████████████████████▀\r\n  ▀█▄   ▐█▌   ▐█▌   ▄█▀\r\n    ▀█▄  ▐█▌ ▐█▌  ▄█▀\r\n      ▀█▄ ▐█ █▌ ▄█▀\r\n     ▀█▄▐█▌▄█▀\r\n          ▀███▀[/color][/size][/tt][/url][/td]\r\n\r\n[td][url=http://volentix.com/][font=arial][size=4pt][color=transparent].[/color][/size]\r\n[size=16pt][color=black]VOLENTIX[/color][/size][/font][/url][/td][td][/td][td][/td]\r\n\r\n[td][center][font=arial][b][size=16pt][url=http://volentix.com/][glow=#232c3b,2,300][color=transparent]...[/color][color=white]Decentralized[/color] [color=#f25a4a]Change[/color][color=transparent]...[/color][/glow][/url][/size]\r\n[size=8pt][color=#f25a4a]▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬[/color]  [url=http://][color=black]ANN[/color][/url][/size][/b][/font][/center][/td][td][/td][td][/td]\r\n\r\n[td][size=6px][color=transparent].[/color][/size]\r\n[url=https://twitter.com/VolentixDAO/][tt][size=2px][color=#232c3b]                ▄█████▄▄    \r\n█▄             ████████████▀ \r\n████▄         █████████████▀ \r\n▀████████▄▄   ████████████\r\n▄▄████████████████████████\r\n █████████████████████████\r\n ▀███████████████████████ \r\n   █████████████████████ \r\n    ▀█████████████████▀\r\n      ▄█████████████▀\r\n▄▄███████████████▀ \r\n   ▀▀▀▀▀▀▀▀▀▀▀[/color][/size][/tt][/url][/td][td][/td]\r\n\r\n[td][size=6px][color=transparent].[/color][/size]\r\n[url=][tt][size=2px][color=#232c3b]                      ▄▄████\r\n                ▄▄▄████████▌\r\n          ▄▄▄███████▀▄█████\r\n     ▄▄█████████▀▀ ▄██████▌\r\n▄▄███████████▀  ▄█████████\r\n ▀▀▀█████▀    ▄██████████▌\r\n       ██   █████████████\r\n        █▄ █████████████▌\r\n        ▐█▄███▀▀████████\r\n         ███▀    ▀▀████▌\r\n                    ▀▀█[/color][/size][/tt][/url][/td][td][/td][td][/td]\r\n\r\n[td][size=2pt][color=#ec6d5a]\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█[/color][/size][/td][td][/td][td][/td]\r\n\r\n[td][center][font=arial][b][size=8pt][color=#232c3b]Analytical Engine • VESPUCCI   |   VCHAIN • Blockchain Technology\r\n[glow=#f25a4a,2,300][color=white][color=transparent]....[/color]▬▬▬▬▬▬▬▬▬  3rd Party DAPP Platform  ▬▬▬▬▬▬▬▬▬[color=transparent]....[/color][/color][/glow]\r\nSocial Rewards Platform • VENUE   |   VDEX • Decentralized Exchange[/color][/size][/b][/font][/center][/td][td][/td][td][/td]\r\n\r\n[td][size=2pt][color=#ec6d5a]\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█\r\n█[/color][/size][/td][td][/td][td][/td]\r\n\r\n[td][center][tt][size=2px]\r\n\r\n\r\n▄▄███████████▄▄\r\n▄█▀▀           ▀▀█▄\r\n▄█    █       █    █▄\r\n█▌    ██     ██    ▐█\r\n█▌    █ █   █ █    ▐█\r\n█▌    █  █ █  █    ▐█\r\n█▌    ▀█▀▀█▀▀█▀    ▐█\r\n▀█      ▀███▀      █▀\r\n▀█▄▄           ▄▄█▀\r\n▀▀███████████▀▀[/size][/tt][/center][/td]\r\n\r\n[td][size=5px][color=transparent].[/color][/size]\r\n[font=arial][b][size=13px][color=#e22b2b]BETA TESTER[/color][/size]\r\n[size=8px]Designed by Zpectrum[/size][/b][/font][/td][/tr][/table][/center]',
        'expected_links': 'http://volentix.com/\r\nhttps://twitter.com/VolentixDAO/',
        'test_signature': 'Simplicity is the ultimate sophistication',
        'image': 'uploads/sig_d51edbec-9989-45c0-8218-52772ab73ae4.png',
        'active': True,
        'date_added': '2018-06-14 12:03:50+00:00'
    },
    {
        'id': 'b0d7c3bb-53bf-4ce7-afcb-b1efea7aa472',
        'name': 'Full Member Design 1',
        'forum_site_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'user_ranks': [
            '99c3f7d6-8adf-4594-a7d3-b64d47488c5a'
        ],
        'code': '[center][font=arial][b][size=8pt][url=http://volentix.com/][color=black][u]     V O L E N T I X[/u][/color][/url]   [color=#f25a4a]█[/color]   [url=http://volentix.com/][color=#232c3b]Decentralized[/color] [color=#f25a4a]Change[/color][/url]   [color=#f25a4a]█[/color]   [url=http://volentix.com/][color=#232c3b]3rd Party DAPP Platform[/color][/url]\r\n[url=http://volentix.com/][color=black]▬ •  VENUE  • ▬[/color]  [color=#232c3b]Social Rewards Platform[/color][/url]   [color=#f25a4a]█[/color]   [url=][color=#232c3b]ANN[/color][/url]   [url=https://twitter.com/VolentixDAO/][color=#232c3b]TWITTER[/color][/url]   [url=][color=#232c3b]TELEGRAM[/color][/url]   [color=#f25a4a]█[/color]   [url=http://volentix.com/][color=black]▬ • VDEX • ▬[/color]  [color=#232c3b]Decentralized Exchange[/color][/url]\r\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬    ( V ) [color=#e22b2b]BETA TESTER[/color]  |  Designed by Zpectrum    ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬[/size][/b][/font][/center]',
        'expected_links': 'http://volentix.com/\r\nhttps://twitter.com/VolentixDAO/',
        'test_signature': 'Whatever you do, do it well',
        'image': 'uploads/sig_deabaa53-8472-48e3-8746-410ea7352fae.png',
        'active': True,
        'date_added': '2018-06-14 12:03:50+00:00'
    },
    {
        'id': 'ac84e67b-077f-453c-a1f8-b63bac745bf3',
        'name': 'Full Member Design 2',
        'forum_site_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'user_ranks': [
            '99c3f7d6-8adf-4594-a7d3-b64d47488c5a'
        ],
        'code': '[center][font=arial][b][size=8pt][color=#ec6d5a]▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬[/color]\r\n[url=https://volentix.com/][color=black]VESPUCCI |[/color] [color=#232c3b]Analytical Engine[/color]  [color=black]►[/color]  [color=black]VENUE |[/color] [color=#232c3b]Social Rewards Platform[/color]     [color=#232c3b]▌[/color]    [color=black]VOLENTIX[/color]  |  [color=#232c3b]Decentralized[/color] [color=#f25a4a]Change[/color]    [color=#232c3b]▐[/color]     [color=black]VDEX |[/color] [color=#232c3b]Decentralized Exchange[/color]  [color=black]◄[/color]  [color=black][u]VCHAIN    [/u][/color][/url]\r\n[color=#ec6d5a]▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬  [color=#232c3b]|  [url=http://][color=#232c3b]ANN[/color][/url]•  [url=https://twitter.com/VolentixDAO/][color=#232c3b]TWITTER[/color][/url]  •  [url=][color=#232c3b]TELEGRAM[/color][/url]   █   [color=#232c3b]( V ) [color=#e22b2b]BETA TESTER[/color]  •[/color]  [color=#232c3b]Designed by Zpectrum[/color]  |  [/color]  ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬[/color][/size][/b][/font][/center]',
        'expected_links': 'https://volentix.com/\r\nhttps://twitter.com/VolentixDAO/',
        'test_signature': 'What we think, we become',
        'image': 'uploads/sig_5f8e0793-63f0-444f-82d0-dd8bf3113ec2.png',
        'active': True,
        'date_added': '2018-06-14 12:03:50+00:00'
    },
    {
        'id': 'c3961d42-e4cb-41a1-862a-54ba2d0463de',
        'name': 'Full Member Design 3',
        'forum_site_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'user_ranks': [
            '99c3f7d6-8adf-4594-a7d3-b64d47488c5a'
        ],
        'code': '[center][font=arial][b][size=8pt][url=http://volentix.com/][color=black][u]          V O L E N T I X[/u][/color][/url]  [color=#232c3b]█[/color]  [url=http://volentix.com/][color=#232c3b]Decentralized[/color] [color=#f25a4a]Change[/color][/url]  [color=#232c3b]█[/color]  ( V ) [color=#e22b2b]BETA TESTER[/color]  ★  Designed by Zpectrum\r\n[color=#f25a4a]▌▌  [url=http://volentix.com/][color=black]3rd Party DAPP Platform[/color][/url]   ▌▌  ▬▬▬▬  [url=http://][color=black]ANN[/color][/url]  [url=https://twitter.com/VolentixDAO/][color=#00aced]Twitter[/color][/url]  [url=][color=#2ca5e0]Telegram[/color][/url]  ▬▬▬▬[/color]\r\n[color=#f25a4a]▌▌[/color]  [url=http://volentix.com/][color=black]Analytical Engine • VESPUCCI[/color]   [color=#f25a4a]|[/color]   [color=black]VCHAIN • Blockchain Technology[/color]  [color=#f25a4a]|[/color]  [color=black]Social Rewards Platform • VENUE[/color]   [color=#f25a4a]|[/color]   [color=black]VDEX • Decentralized Exchange[/color][/url]   [color=#f25a4a]▌▌[/color][/size][/b][/font][/center]',
        'expected_links': 'http://volentix.com/\r\nhttps://twitter.com/VolentixDAO/',
        'test_signature': 'All limitations are self-imposed',
        'image': 'uploads/sig_2a615f06-e124-4727-aa3e-64672d6d9617.png',
        'active': True,
        'date_added': '2018-06-14 12:03:50+00:00'
    }
]


def add_signatures(apps, schema_editor):
    Signature = apps.get_model('venue', 'Signature')
    for sig_details in SIGNATURES:
        rank = Signature(**sig_details)
        rank.save()


FORUM_PROFILES = [
    {
        'id': 'b772b2f2-2e9f-4139-859c-933abe8e6ba2',
        'forum_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'forum_rank_id': 'dd1bbfa7-a3c3-4163-8c0d-b04eb84db9ad',
        'forum_username': 'stingray',
        'forum_user_id': '2299143',
        'signature_id': '0a7dd7cd-8f3b-48ca-989c-d4ec550b136d',
        'verification_code': '1N5IwKzZ',
        'active': True,
        'verified': True,
        'date_verified': '2018-06-14 12:48:05+00:00',
        'date_added': '2018-06-14 12:37:54+00:00',
        'date_updated': '2018-06-16 07:24:09.271000+00:00',
        'dummy': True,
        'signature_found': True
    },
    {
        'id': '709bc479-a411-40df-bc9a-7564da0f521e',
        'forum_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'forum_rank_id': '99c3f7d6-8adf-4594-a7d3-b64d47488c5a',
        'forum_username': 'spiderman',
        'forum_user_id': '8271817',
        'signature_id': 'ac84e67b-077f-453c-a1f8-b63bac745bf3',
        'verification_code': 'ewWsQjxl',
        'active': True,
        'verified': True,
        'date_verified': '2018-06-14 14:27:16+00:00',
        'date_added': '2018-06-14 14:26:43+00:00',
        'date_updated': '2018-06-16 07:25:34.201000+00:00',
        'dummy': True,
        'signature_found': True
    },
    {
        'id': '480dd458-9325-44ca-a4a2-ee4c0ccfa173',
        'forum_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'forum_rank_id': '99c3f7d6-8adf-4594-a7d3-b64d47488c5a',
        'forum_username': 'antman',
        'forum_user_id': '1319410',
        'signature_id': 'ac84e67b-077f-453c-a1f8-b63bac745bf3',
        'verification_code': '1dnS82lj',
        'active': True,
        'verified': True,
        'date_verified': '2018-06-10 03:34:27+00:00',
        'date_added': '2018-06-10 03:19:07+00:00',
        'date_updated': '2018-06-16 07:22:32.686000+00:00',
        'dummy': True,
        'signature_found': True
    },
    {
        'id': '6b4d6821-ccba-41a9-8625-2a1da174b93d',
        'forum_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'forum_rank_id': '99c3f7d6-8adf-4594-a7d3-b64d47488c5a',
        'forum_username': 'hawkeye',
        'forum_user_id': '1544937',
        'signature_id': 'b0d7c3bb-53bf-4ce7-afcb-b1efea7aa472',
        'verification_code': '1Q7h8pk7',
        'active': True,
        'verified': True,
        'date_verified': '2018-06-10 03:33:13+00:00',
        'date_added': '2018-06-10 03:19:07+00:00',
        'date_updated': '2018-06-16 07:25:20.047000+00:00',
        'dummy': True,
        'signature_found': True
    },
    {
        'id': 'ce52c2f5-ae68-4a31-83a5-01f96de5d78f',
        'forum_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'forum_rank_id': 'dd1bbfa7-a3c3-4163-8c0d-b04eb84db9ad',
        'forum_username': 'hulk',
        'forum_user_id': '1058231',
        'signature_id': '0a7dd7cd-8f3b-48ca-989c-d4ec550b136d',
        'verification_code': 'eDxcn2KX',
        'active': True,
        'verified': True,
        'date_verified': '2018-06-10 03:32:37+00:00',
        'date_added': '2018-06-10 03:19:07+00:00',
        'date_updated': '2018-06-16 07:25:51.218000+00:00',
        'dummy': True,
        'signature_found': True
    },
    {
        'id': 'bd57efbc-9b53-4c85-9e05-5f593b96581d',
        'forum_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'forum_rank_id': '99c3f7d6-8adf-4594-a7d3-b64d47488c5a',
        'forum_username': 'ironman',
        'forum_user_id': '2552354',
        'signature_id': 'ac84e67b-077f-453c-a1f8-b63bac745bf3',
        'verification_code': '1XXCzjmA',
        'active': True,
        'verified': True,
        'date_verified': '2018-06-10 03:32:08+00:00',
        'date_added': '2018-06-10 03:19:07+00:00',
        'date_updated': '2018-06-16 03:53:43.877000+00:00',
        'dummy': True,
        'signature_found': True
    },
    {
        'id': '19bb3f6b-52b6-4651-947e-b99c2566049b',
        'forum_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'forum_rank_id': '14d22df0-3462-492b-81c5-b5812d3ef777',
        'forum_username': 'thor',
        'forum_user_id': '1216831',
        'signature_id': 'c3961d42-e4cb-41a1-862a-54ba2d0463de',
        'verification_code': 'VAyig4md',
        'active': True,
        'verified': True,
        'date_verified': '2018-06-10 03:31:44+00:00',
        'date_added': '2018-06-10 03:19:07+00:00',
        'date_updated': '2018-06-16 07:42:46.570000+00:00',
        'dummy': True,
        'signature_found': True
    },
    {
        'id': '404a09b4-34ce-4a54-a52e-af815d289b31',
        'forum_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'forum_rank_id': '99c3f7d6-8adf-4594-a7d3-b64d47488c5a',
        'forum_username': 'silverclaw',
        'forum_user_id': '2796746',
        'signature_id': 'ac84e67b-077f-453c-a1f8-b63bac745bf3',
        'verification_code': '1ZLFBW9q',
        'active': True,
        'verified': True,
        'date_verified': '2018-06-10 03:30:35+00:00',
        'date_added': '2018-06-10 03:19:07+00:00',
        'date_updated': '2018-06-16 03:53:29.320000+00:00',
        'dummy': True,
        'signature_found': True
    },
    {
        'id': 'b759e131-192f-4656-b977-3f6010900528',
        'forum_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'forum_rank_id': 'dd1bbfa7-a3c3-4163-8c0d-b04eb84db9ad',
        'forum_username': 'nomad',
        'forum_user_id': '1306970',
        'signature_id': '764ab6b6-fb92-40ad-839c-4f26ee86eed8',
        'verification_code': 'eLxu55pW',
        'active': True,
        'verified': True,
        'date_verified': '2018-06-10 03:29:00+00:00',
        'date_added': '2018-06-10 03:19:07+00:00',
        'date_updated': '2018-06-16 03:53:18.016000+00:00',
        'dummy': True,
        'signature_found': True
    },
    {
        'id': '5bb143a4-22e1-4ba6-b14b-00235595f585',
        'forum_id': '4b8b11d1-14bb-46a7-ac8b-397587235b28',
        'forum_rank_id': '14d22df0-3462-492b-81c5-b5812d3ef777',
        'forum_username': 'wolverine',
        'forum_user_id': '1551606',
        'signature_id': '5a506e4d-f5b6-408e-9e00-39f5b7521351',
        'verification_code': '18pTZWDa',
        'active': True,
        'verified': True,
        'date_verified': '2018-06-10 03:27:46+00:00',
        'date_added': '2018-06-10 03:27:56+00:00',
        'date_updated': '2018-06-16 03:53:08.829000+00:00',
        'dummy': True,
        'signature_found': True
    }
]


def add_forum_profiles(apps, schema_editor):
    UserProfile = apps.get_model('venue', 'UserProfile')
    ForumProfile = apps.get_model('venue', 'ForumProfile')
    for fp_details in FORUM_PROFILES:
        fp_details['user_profile'] = UserProfile.objects.get(
            user__username=fp_details['forum_username']
        )
        fp_details['last_scrape'] = timezone.now()
        forum_profile = ForumProfile(**fp_details)
        forum_profile.save()


FORUM_POSTS = [
    {'base_points': '100.00', 'credited': True, 'date_credited': '2018-06-14 14:32:28+00:00', 'date_matured': '2018-06-14 14:32:30+00:00', 'influence_bonus_pct': '0.00', 'influence_bonus_pts': '0.00', 'invalid_sig_minutes': 0, 'matured': True, 'message_id': '40108455', 'timestamp': '2018-06-13 14:18:40+00:00', 'topic_id': '4083764', 'total_points': '100.00', 'unique_content_length': 298, 'valid_sig_minutes': 1440, 'forum_profile_id': 'b772b2f2-2e9f-4139-859c-933abe8e6ba2', 'forum_rank_id': 'bc8bb1b2-e056-47ab-bcf1-7967a27dd6b4'},
    {'base_points': '100.00', 'credited': True, 'date_credited': '2018-06-14 14:31:56+00:00', 'date_matured': '2018-06-14 14:31:58+00:00', 'influence_bonus_pct': '0.00', 'influence_bonus_pts': '0.00', 'invalid_sig_minutes': 40, 'matured': True, 'message_id': '40109083', 'timestamp': '2018-06-13 14:29:15+00:00', 'topic_id': '4469212', 'total_points': '100.00', 'unique_content_length': 145, 'valid_sig_minutes': 1400, 'forum_profile_id':'709bc479-a411-40df-bc9a-7564da0f521e', 'forum_rank_id': 'bc8bb1b2-e056-47ab-bcf1-7967a27dd6b4'},
    {'base_points': '100.00', 'credited': True, 'date_credited': '2018-06-14 14:37:20+00:00', 'date_matured': '2018-06-14 14:37:18+00:00', 'influence_bonus_pct': '0.00', 'influence_bonus_pts': '0.00', 'invalid_sig_minutes': 0, 'matured': True, 'message_id': '40109519', 'timestamp': '2018-06-13 14:36:44+00:00', 'topic_id': '4468464', 'total_points': '100.00', 'unique_content_length': 121, 'valid_sig_minutes': 1440, 'forum_profile_id': 'b772b2f2-2e9f-4139-859c-933abe8e6ba2', 'forum_rank_id': 'bc8bb1b2-e056-47ab-bcf1-7967a27dd6b4'},
    {'base_points': '100.00', 'credited': True, 'date_credited': '2018-06-13 04:25:08+00:00', 'date_matured': '2018-06-13 04:20:08+00:00', 'influence_bonus_pct': '5.00', 'influence_bonus_pts': '5.00', 'invalid_sig_minutes': 0, 'matured': True, 'message_id': '39923976', 'timestamp': '2018-06-12 04:20:08+00:00', 'topic_id': '3830642', 'total_points': '105.00', 'unique_content_length': 554, 'valid_sig_minutes': 1440, 'forum_profile_id': '5bb143a4-22e1-4ba6-b14b-00235595f585', 'forum_rank_id': '14d22df0-3462-492b-81c5-b5812d3ef777'},
    {'base_points': '100.00', 'credited': True, 'date_credited': '2018-06-12 06:59:21+00:00', 'date_matured': '2018-06-12 06:58:21+00:00', 'influence_bonus_pct': '2.00', 'influence_bonus_pts': '2.00', 'invalid_sig_minutes': 64, 'matured': True, 'message_id': '818272', 'timestamp': '2018-06-11 06:58:21+00:00', 'topic_id': '7281', 'total_points': '102.00', 'unique_content_length': 210, 'valid_sig_minutes': 1376, 'forum_profile_id': 'b772b2f2-2e9f-4139-859c-933abe8e6ba2', 'forum_rank_id': 'dd1bbfa7-a3c3-4163-8c0d-b04eb84db9ad'},
    {'base_points': '100.00', 'credited': True, 'date_credited': '2018-06-12 07:04:48+00:00', 'date_matured': '2018-06-12 07:04:43+00:00', 'influence_bonus_pct': '2.00', 'influence_bonus_pts': '2.00', 'invalid_sig_minutes': 0, 'matured': True, 'message_id': '213422', 'timestamp': '2018-06-11 07:04:09+00:00', 'topic_id': '234', 'total_points': '102.00', 'unique_content_length': 319, 'valid_sig_minutes': 1440, 'forum_profile_id': 'b772b2f2-2e9f-4139-859c-933abe8e6ba2', 'forum_rank_id': 'dd1bbfa7-a3c3-4163-8c0d-b04eb84db9ad'},
    {'base_points': '100.00', 'credited': True, 'date_credited': '2018-06-13 07:06:09+00:00', 'date_matured': '2018-06-13 07:06:05+00:00', 'influence_bonus_pct': '2.00', 'influence_bonus_pts': '2.00', 'invalid_sig_minutes': 60, 'matured': True, 'message_id': '563441', 'timestamp': '2018-06-12 07:05:57+00:00', 'topic_id': '443', 'total_points': '102.00', 'unique_content_length': 187, 'valid_sig_minutes': 1380, 'forum_profile_id': 'b772b2f2-2e9f-4139-859c-933abe8e6ba2', 'forum_rank_id': 'dd1bbfa7-a3c3-4163-8c0d-b04eb84db9ad'},
    {'base_points': '100.00', 'credited': True, 'date_credited': '2018-06-16 07:21:44+00:00', 'date_matured': '2018-06-16 07:21:38+00:00', 'influence_bonus_pct': '0.00', 'influence_bonus_pts': '0.00', 'invalid_sig_minutes': 0, 'matured': True, 'message_id': '1283829', 'timestamp': '2018-06-15 07:21:32+00:00', 'topic_id': '968', 'total_points': '100.00', 'unique_content_length': 58, 'valid_sig_minutes': 1440, 'forum_profile_id': '480dd458-9325-44ca-a4a2-ee4c0ccfa173', 'forum_rank_id': '99c3f7d6-8adf-4594-a7d3-b64d47488c5a'},
    {'base_points': '100.00', 'credited': True, 'date_credited': '2018-06-16 07:28:53+00:00', 'date_matured': '2018-06-16 07:28:51+00:00', 'influence_bonus_pct': '0.00', 'influence_bonus_pts': '0.00', 'invalid_sig_minutes': 0, 'matured': True, 'message_id': '7853723', 'timestamp': '2018-06-15 07:28:45+00:00', 'topic_id': '865', 'total_points': '100.00', 'unique_content_length': 321, 'valid_sig_minutes': 1440, 'forum_profile_id': '6b4d6821-ccba-41a9-8625-2a1da174b93d', 'forum_rank_id': '99c3f7d6-8adf-4594-a7d3-b64d47488c5a'},
    {'base_points': '100.00', 'credited': True, 'date_credited': '2018-06-14 07:35:26+00:00', 'date_matured': '2018-06-14 07:35:15+00:00', 'influence_bonus_pct': '2.00', 'influence_bonus_pts': '2.00', 'invalid_sig_minutes': 40, 'matured': True, 'message_id': '8537231', 'timestamp': '2018-06-13 07:35:11+00:00', 'topic_id': '362', 'total_points': '102.00', 'unique_content_length': 256, 'valid_sig_minutes': 1400, 'forum_profile_id': 'ce52c2f5-ae68-4a31-83a5-01f96de5d78f', 'forum_rank_id': 'dd1bbfa7-a3c3-4163-8c0d-b04eb84db9ad'},
    {'base_points': '100.00', 'credited': True, 'date_credited': '2018-06-16 07:37:24+00:00', 'date_matured': '2018-06-16 07:37:21+00:00', 'influence_bonus_pct': '0.00', 'influence_bonus_pts': '0.00', 'invalid_sig_minutes': 0, 'matured': True, 'message_id': '7562617', 'timestamp': '2018-06-15 07:37:15+00:00', 'topic_id': '124', 'total_points': '100.00', 'unique_content_length': 67, 'valid_sig_minutes': 1440, 'forum_profile_id': 'bd57efbc-9b53-4c85-9e05-5f593b96581d', 'forum_rank_id': '99c3f7d6-8adf-4594-a7d3-b64d47488c5a'},
    {'base_points': '100.00', 'credited': True, 'date_credited': '2018-06-13 07:39:19+00:00', 'date_matured': '2018-06-13 07:39:14+00:00', 'influence_bonus_pct': '2.00', 'influence_bonus_pts': '2.00', 'invalid_sig_minutes': 0, 'matured': True, 'message_id': '7843626', 'timestamp': '2018-06-12 07:39:09+00:00', 'topic_id': '432', 'total_points': '102.00', 'unique_content_length': 290, 'valid_sig_minutes': 1440, 'forum_profile_id': 'b759e131-192f-4656-b977-3f6010900528', 'forum_rank_id': 'dd1bbfa7-a3c3-4163-8c0d-b04eb84db9ad'},
    {'base_points': '100.00', 'credited': True, 'date_credited': '2018-06-15 07:41:06+00:00', 'date_matured': '2018-06-15 07:41:00+00:00', 'influence_bonus_pct': '0.00', 'influence_bonus_pts': '0.00', 'invalid_sig_minutes': 0, 'matured': True, 'message_id': '7262621', 'timestamp': '2018-06-14 07:40:53+00:00', 'topic_id': '746', 'total_points': '100.00', 'unique_content_length': 90, 'valid_sig_minutes': 1440, 'forum_profile_id': '404a09b4-34ce-4a54-a52e-af815d289b31', 'forum_rank_id': '99c3f7d6-8adf-4594-a7d3-b64d47488c5a'},
    {'base_points': '100.00', 'credited': True, 'date_credited': '2018-06-15 07:42:27+00:00', 'date_matured': '2018-06-15 07:42:23+00:00', 'influence_bonus_pct': '5.00', 'influence_bonus_pts': '5.00', 'invalid_sig_minutes': 0, 'matured': True, 'message_id': '7362618', 'timestamp': '2018-06-14 07:42:17+00:00', 'topic_id': '737', 'total_points': '105.00', 'unique_content_length': 230, 'valid_sig_minutes': 1440, 'forum_profile_id': '19bb3f6b-52b6-4651-947e-b99c2566049b', 'forum_rank_id': '14d22df0-3462-492b-81c5-b5812d3ef777'}
]


def add_forum_posts(apps, schema_editor):
    ForumPost = apps.get_model('venue', 'ForumPost')
    ForumProfile = apps.get_model('venue', 'ForumProfile')
    for post_details in FORUM_POSTS:
        fp = ForumProfile.objects.get(id=post_details['forum_profile_id'])
        post_details['user_profile'] = fp.user_profile
        forum_post = ForumPost(**post_details)
        forum_post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_users),
        migrations.RunPython(add_languages),
        migrations.RunPython(add_forum_sites),
        migrations.RunPython(add_user_profiles),
        migrations.RunPython(add_forum_user_ranks),
        migrations.RunPython(add_signatures),
        migrations.RunPython(add_forum_profiles),
        migrations.RunPython(add_forum_posts)
    ]
