# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-08 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postuptimestats',
            name='user_post_stats',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='uptime_stats', to='venue.UserPostStats'),
        ),
    ]
