# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-27 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumprofile',
            name='last_scrape',
            field=models.DateTimeField(null=True),
        ),
    ]
