# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-19 04:05
from __future__ import unicode_literals

from django.db import migrations


LANGUAGES = [
    {
        'name': 'English',
        'code': 'en'
    }
]


def add_languages(apps, schema_editor):
    Language = apps.get_model('venue', 'Language')
    for language in LANGUAGES:
        Language.objects.get_or_create(
            name='English',
            code='en'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_languages)
    ]
