# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-09 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_auto_20180508_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postuptimestats',
            old_name='invalid_sig_minutes',
            new_name='invalid_sig_seconds',
        ),
        migrations.RenameField(
            model_name='postuptimestats',
            old_name='valid_sig_minutes',
            new_name='valid_sig_seconds',
        ),
    ]
