# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-12 04:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_auto_20180710_0208'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forumprofile',
            unique_together=set([]),
        ),
    ]
