# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_auto_20171026_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointscalculation',
            name='influence_points',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pointscalculation',
            name='post_days_points',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pointscalculation',
            name='post_points',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pointscalculation',
            name='total_points',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
