# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-29 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_auto_20180619_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='batch',
            field=models.IntegerField(default=1),
        ),
    ]
