# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_auto_20171029_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumprofile',
            name='date_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forumprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='forumprofile',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
