# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import venue.models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0003_auto_20171101_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='image',
            field=models.ImageField(blank=True, upload_to=venue.models.image_file_name),
        ),
    ]
