# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0003_auto_20171026_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointscalculation',
            name='signature_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_calculations', to='venue.SignatureCheck'),
        ),
    ]
