# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-29 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0003_ranking_batch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpost',
            options={'get_latest_by': 'timestamp'},
        ),
        migrations.AlterModelOptions(
            name='forumprofile',
            options={'get_latest_by': 'date_updated'},
        ),
        migrations.AlterModelOptions(
            name='ranking',
            options={'get_latest_by': 'timestamp'},
        ),
    ]
