# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-16 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0003_auto_20180712_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='monitoring',
            field=models.BooleanField(default=True),
        ),
    ]
