# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_auto_20171124_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturecheck',
            name='initial',
            field=models.BooleanField(default=False),
        ),
    ]
