# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-16 12:28
from __future__ import unicode_literals

from django.db import migrations


def update_forum_posts(apps, schema_editor):
    ForumPost = apps.get_model('venue', 'ForumPost')
    ForumPost.objects.filter(matured=True).update(monitoring=False)


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_forumpost_monitoring'),
    ]

    operations = [
        migrations.RunPython(update_forum_posts)
    ]
