# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_signature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumprofile',
            name='profile_url',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forumprofile',
            name='forum_user_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
