# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-31 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_auto_20180531_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumuserrank',
            name='bonus_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
