# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-01 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0005_forumuserrank_bonus_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='date_credited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='date_matured',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
