# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-30 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0005_auto_20180630_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='expected_links',
        ),
    ]
