# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0005_auto_20171103_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumprofile',
            old_name='date_joined',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='forumprofile',
            name='signature_code',
        ),
    ]
