# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-11 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0006_ranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumprofile',
            name='initial_posts_count',
        ),
    ]
