# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0006_auto_20171201_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturecheck',
            name='status_code',
            field=models.IntegerField(default=202),
            preserve_default=False,
        ),
    ]
