# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-14 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import venue.models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0006_auto_20180601_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='forum_rank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='venue.ForumUserRank'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signature',
            name='image',
            field=models.ImageField(default='media/uploads/img/signature_img.png', upload_to=venue.models.image_file_name),
        ),
    ]
