# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-26 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


def create_referral_default_value(apps, schema_editor):
    user_profile_model = apps.get_model('venue', 'userprofile')
    for user_profile in user_profile_model.objects.all():
        user_profile.referral_code = uuid.uuid4()
        user_profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0006_auto_20180724_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.UUIDField(default=None, blank=True, null=True),
        ),
        migrations.RunPython(create_referral_default_value),
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referrer',
            field=models.ForeignKey(blank=True, db_column='referrer', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='venue.UserProfile', to_field='referral_code'),
        ),
    ]
