# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-06 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0007_auto_20180705_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='credited',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='date_credited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
