# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0007_signaturecheck_status_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rank', models.IntegerField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='venue.UserProfile')),
            ],
        ),
    ]
