# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-28 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0007_auto_20180726_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('granted', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('referral', models.ForeignKey(help_text='User, that was registered with a referral code', on_delete=django.db.models.deletion.CASCADE, related_name='referrer', to='venue.UserProfile', unique=True)),
                ('referrer', models.ForeignKey(help_text='Owner of a referral code', on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='venue.UserProfile')),
            ],
        ),
    ]
