# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-16 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0007_auto_20180614_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumprofile',
            name='dummy',
            field=models.BooleanField(default=False),
        ),
    ]
