# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-24 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0007_remove_forumprofile_initial_posts_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='receive_emails',
            field=models.BooleanField(default=False),
        ),
    ]
