# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-28 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0007_auto_20180726_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('granted', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('referral', models.OneToOneField(help_text='User, that was registered with a referral code', on_delete=django.db.models.deletion.CASCADE, related_name='referrer', to='venue.UserProfile')),
                ('referrer', models.ForeignKey(help_text='Owner of a referral code', on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='venue.UserProfile')),
            ],
        ),
    ]
