# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-06 09:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0008_auto_20180706_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumprofile',
            name='last_page_status',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
