# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0008_forumprofile_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumprofile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
