# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0009_auto_20171111_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumUserRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='forumprofile',
            name='forum_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='venue.ForumUserRank'),
        ),
    ]
