# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0009_auto_20171209_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturecheck',
            name='new_posts',
            field=models.IntegerField(default=0),
        ),
    ]
