# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0010_signaturecheck_new_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumprofile',
            name='forum_username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
