# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-06 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0010_auto_20180706_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumprofile',
            name='signature_found',
        ),
    ]
