# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0010_auto_20171111_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='expected_links',
            field=models.TextField(blank=True),
        ),
    ]
