# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0011_signature_expected_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumuserrank',
            name='forum_site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='venue.ForumSite'),
            preserve_default=False,
        ),
    ]
