# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-18 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0011_userprofile_language_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
