# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-18 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0012_auto_20180818_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='language_code',
            new_name='language',
        ),
    ]
