# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-28 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0013_auto_20180818_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('campaign_start', models.DateTimeField(null=True)),
                ('campaign_end', models.DateTimeField(null=True)),
            ],
        ),
    ]
