# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0013_uptimebatch_reason_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uptimebatch',
            name='reason_closed',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
