# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0013_signature_user_ranks'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumuserrank',
            name='allowed',
            field=models.BooleanField(default=False),
        ),
    ]
