# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-30 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0014_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
