# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0014_forumuserrank_allowed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forumprofile',
            unique_together=set([('forum', 'forum_user_id', 'verified')]),
        ),
    ]
