# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0015_auto_20180830_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verto_address',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
