# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-09 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0015_userprofile_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enabled_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
