# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0015_auto_20171116_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumprofile',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
