# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-15 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0017_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='variant',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info')], default='info', max_length=10),
            preserve_default=False,
        ),
    ]
