# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-15 12:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0018_notification_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='dismissed_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
