# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-17 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0020_notification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='uptimebatch',
            name='num_deleted_posts',
            field=models.IntegerField(default=0),
        ),
    ]
