# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-03 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0021_uptimebatch_num_deleted_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='test_signature',
            field=models.TextField(blank=True),
        ),
    ]
