# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-03 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import venue.models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0022_signature_test_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignaturePoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('post_addition', 'Post addition'), ('post_deletion', 'Post deletion'), ('post_uptime', 'Uptime')], default='uptime', max_length=30)),
                ('posts_count', models.IntegerField()),
                ('points', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('forum_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points', to='venue.ForumProfile')),
                ('uptime_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points', to='venue.UptimeBatch')),
            ],
        ),
        migrations.AlterField(
            model_name='signature',
            name='image',
            field=models.ImageField(default='static/img/signature_img.png', upload_to=venue.models.image_file_name),
        ),
        migrations.AddIndex(
            model_name='signaturepoints',
            index=models.Index(fields=['category'], name='category'),
        ),
        migrations.AddIndex(
            model_name='signaturepoints',
            index=models.Index(fields=['timestamp'], name='timestamp'),
        ),
    ]
