# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-04 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0023_auto_20180503_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signaturepoints',
            options={'verbose_name_plural': 'Signature points'},
        ),
        migrations.AddField(
            model_name='signaturepoints',
            name='signature_check',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='points', to='venue.SignatureCheck'),
            preserve_default=False,
        ),
    ]
