# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-07 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0024_auto_20180504_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturepoints',
            name='points',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
