apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: django-service
  labels:
    application: django-service
spec:
  replicas: 1
  selector:
    matchLabels:
      application: django-service
  template:
    metadata:
      labels:
        application: django-service
        pod: django-service
    spec:
      containers:
      - args:
        - supervisord
        - -c
        - ./supervisord.conf
        - --nodaemon
        command:
        - /entrypoint.sh
        name: django-service
        image: volentixlabs/venueserver:v0.0.16-beta
        ports:
        - containerPort: 8000
          # This name will be used in the Service.
          name: backend-http
        - containerPort: 9000
        - containerPort: 5555
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: user

          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: password
          
          - name: POSTGRES_NAME
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: databasename
          
          - name: POSTGRES_HOST
            value: postgres-service

          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: redis-credentials
                key: host

          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-credentials
                key: password
---
# Service definition for a http/https service.
apiVersion: v1
kind: Service
metadata:
  name: django-service
  annotations:
    # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # TODO: Fill in with the ARN of your certificate.
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert:  arn:aws:acm:ca-central-1:854376586701:certificate/380d528a-555f-4673-904b-0c2cdc6758d9
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  type: LoadBalancer
  loadBalancerIP:
  ports:
  - port: 80
    name: http
    # Use named container port.
    targetPort: backend-http
  - port: 443
    name: https
    # Use named container port.
    targetPort: backend-http
  selector:
    application: django-service

